name: C-Mark
favicon: null
layout_spectrum: 0.6978386705741286
typography_spectrum: 0.03372404491528869
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.1982770375907421
  lightness: 0.8661635078024119
  saturation: 0.7372813511174172
  rhythmicContrast: 0.2915665633045137
purpose: []
